repos:
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.6.1
    hooks:
    - id: reorder-python-imports
      language_version: python3.7
      types: [python]
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.7
      types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      language_version: python3.7
      types: [python]

